### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by chuxiaaaa** [cmooref17/ReservedItemSlotMods#21]
This is not your problem. The reason for this issue is that some localization mods in the game change item names, which can cause itemProperties.itemName to not match the slotName.

It is recommended to change it to determine the item type, or add a new config option that allows the player to customize the name of the side panel item...

**Comment by chuxiaaaa** [comment]
Incidentally, when there's a player in the room using this mod, it causes my anti-cheat to not be able to get the actual item in hand, but this issue doesn't always happen

**Comment by cmooref17** [comment]
In the latest versions of my mod, you can add custom item names, and I have a statement on each of my mod pages explaining that if using translation mods, you may have to add the translated item names to the config.

And it's not easy to categorize items by type, since there aren't often similarities between items added in the slots. This would work for the flashlight slot mod, but not for the rest of them.

For now, adding the new item names to the config is the best solution if using a localization mod, until I have time to work something else out.

**Comment by chuxiaaaa** [comment]
> In the latest versions of my mod, you can add custom item names, and I have a statement on each of my mod pages explaining that if using translation mods, you may have to add the translated item names to the config.
> 
> And it's not easy to categorize items by type, since there aren't often similarities between items added in the slots. This would work for the flashlight slot mod, but not for the rest of them.
> 
> For now, adding the new item names to the config is the best solution if using a localization mod, until I have time to work something else out.

Sorry, I didn't really look at the README file, but adding an optional item type to ReservedItemSlotData might solve the problem without the player having to configure it. Since some players (including me before) currently think the current version is buggy, they don't check the README to change their configurations or anything like that, and then just fall back to the old version

**Comment by cmooref17** [comment]
Just a quick update, but I created a map for items that will link and item's "data" to the original name, and I tested with a chinese localization mod, and this seems to have fixed this issue. I was able to pick up a flashlight into the reserved flashlight slot without having to add the translated name in the config. This will be working on ReservedItemSlotCore 2.0.10. Hope this helps!
